{% set name = "arosics" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2eeebd1b422dc4cfce819fabb7b3e52ec54d00e7fdb1acb2bf15c8d22a28757

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - cmocean
    - folium >=0.6.0
    - gdal
    - geoarray >=0.9.0
    - geojson
    - geopandas
    - holoviews
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pyfftw
    - pykrige
    - py-tools-ds >=0.14.28
    - python
    - scikit-image
    - shapely
    - six

test:
  imports:
    - arosics
    - arosics.CoReg
    - arosics.CoReg_local
    - arosics.DeShifter
    - arosics.geometry
    - arosics.plotting
    - arosics.Tie_Point_Grid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/arosics/
  summary: An Automated and Robust Open-Source Image Co-Registration Software for Multi-Sensor Satellite Data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
