{% set name = "arosics" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cdb8ce2f6c2264140e89dfd8a0d67e4161782fc18bf14227201af5dd92b5ca54

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arosics = arosics.arosics_cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - colorama  # [win]  # missing upstream dependency (holoviews > panel > tqdm > colorama)
    - cmocean
    - folium >=0.6.0,!=0.12.0
    - gdal
    - geoarray >=0.13.4
    - geojson
    - geopandas
    - holoviews
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pyfftw
    - pykrige
    - pyproj >2.2.0
    - py-tools-ds >=0.17.8
    - python
    - scikit-image >=0.16.0
    - shapely

test:
  imports:
    - arosics
    - arosics.CoReg
    - arosics.CoReg_local
    - arosics.DeShifter
    - arosics.geometry
    - arosics.plotting
    - arosics.Tie_Point_Grid
  commands:
    - pip check
    - arosics --help
  requires:
    - pip

about:
  home: https://pypi.org/project/arosics/
  summary: An Automated and Robust Open-Source Image Co-Registration Software for Multi-Sensor Satellite Data
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
