{% set name = "arosics" %}
{% set version = "1.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7ecd5cbf1fbb255fcfc9b149c561c8211c77244a27e591dbad1c5cfac841972

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arosics = arosics.arosics_cli:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - cmocean
    - folium >=0.6.0,!=0.12.0
    - gdal
    - geoarray >=0.15.0
    - geojson
    - geopandas
    - holoviews >1.12.7
    - joblib >=1.3.0
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pykrige
    - pyproj >2.2.0
    - py-tools-ds >=0.18.0
    - python
    - scikit-image >=0.21.0
    - scikit-learn
    - scipy >=1.7.0
    - shapely

test:
  imports:
    - arosics
    - arosics.CoReg
    - arosics.CoReg_local
    - arosics.DeShifter
    - arosics.geometry
    - arosics.plotting
    - arosics.Tie_Point_Grid
  commands:
    - pip check
    - arosics --help
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/danschef/arosics
  summary: An Automated and Robust Open-Source Image Co-Registration Software for Multi-Sensor Satellite Data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
