{% set name = "arosics" %}
{% set version = "0.9.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7bf21eb48be390456770f3d05d925f08806f70d35bea7cd8c2c6475673c66835

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - matplotlib-base
  run:
    - cmocean
    - folium >=0.6.0
    - gdal
    - geoarray >=0.8.30
    - geojson
    - geopandas
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - py-tools-ds >=0.14.28
    - python
    - scikit-image
    - shapely
    - six

test:
  imports:
    - arosics

about:
  home: https://pypi.org/project/arosics/
  summary: An Automated and Robust Open-Source Image Co-Registration Software for Multi-Sensor Satellite Data
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rluria14
    - ndmaxar
    - RyanHackney
