{% set name = "arosics" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 947c9025aa10a230696d7550b738b095b9f54085e3f6bf3da6fee1278d865f26

build:
  number: 0
  skip: true  # [py<37 and not osx]
  skip: true  # [py<38 and osx]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - arosics = arosics.arosics_cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools-git
  run:
    - cartopy
    - cmocean
    - folium >=0.6.0,!=0.12.0
    - gdal
    - geoarray >=0.15.0
    - geojson
    - geopandas
    - holoviews
    - matplotlib-base
    - numpy
    - pandas
    - plotly
    - pyfftw <0.13.0|=0.13.0=*0  # https://github.com/pyFFTW/pyFFTW/issues/294
    - pykrige
    - pyproj >2.2.0
    - py-tools-ds >=0.18.0
    - python
    - scikit-image >=0.16.0
    - shapely

test:
  imports:
    - arosics
    - arosics.CoReg
    - arosics.CoReg_local
    - arosics.DeShifter
    - arosics.geometry
    - arosics.plotting
    - arosics.Tie_Point_Grid
  commands:
    - pip check
    - arosics --help
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/danschef/arosics
  summary: An Automated and Robust Open-Source Image Co-Registration Software for Multi-Sensor Satellite Data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - danschef
    - rluria14
    - ndmaxar
    - RyanHackney
